language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
deploy:
  provider: netlify
    site: https://projektihklandingpage.netlify.com/
    auth: 9d1b530b-6c15-427f-ae38-be0d4836cebf
    edge: true # opt in to dpl v2
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - ""
after_success:
  - "npm run deploy"