language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 013b793523d7adb15dd419a13129e4180c4e28d3
  local_dir: public
  keep-history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - ""
after_success:
  - "npm run deploy"